# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
source:       ./bootstrap/docs
destination:  ./bootstrap
#url:          http://bootstrap.dev:9001
#server_port:  9001
lsi: false
pygments: true